### GET /
GET http://localhost:5000

### Register a new user POST /Auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "khush@domain.com",
    "password": "securepassword"
}


### Login a user POST /Auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "khush@domain.com",
    "password": "securepassword"
}